@HighScore.API_HostAddress = https://localhost:58965/

GET {{HighScore.API_HostAddress}}/

### Fyll på med en Guid för en spelare
GET {{HighScore.API_HostAddress}}/{00000000-0000-0000-0000-000000000000}

### 
GET {{HighScore.API_HostAddress}}/top-five

###
POST {{HighScore.API_HostAddress}}/
Content-Type: application/json

{
    "PlayerId": "00000000-0000-0000-0000-000000000000",
    "Score": 100
}